### ISSUE TITLE
Does not allow login

### ISSUE THREAD

**Issue by andrfgs** [paysonwallach/aqua-lightdm-webkit-theme#10]
I can't login with this theme. Whenever I press enter or click the arrow to login with a correct key nothing happens. A failed password produces the "shake" animation but a correct password seems to do nothing.

Everything else seems to be working fine. I am using my MSI laptop, with a steelseries keyboard incorporated (could it be a driver issue? but clicking the arrow also does nothing)

Distro: Arch Linux
Kernel Version: 5.3.8

**Comment by paysonwallach** [comment]
I'm sorry you're having trouble logging in. Are you able to log in using other themes? Also, are there any errors given in `/var/log/lightdm/lightdm.log`? Finally, I don't believe a driver issue is likely, unless you're having trouble with other themes or display managers.

**Comment by andrfgs** [comment]
<details>
<summary>Lightdm Log</summary>

> [+0.00s] DEBUG: Logging to /var/log/lightdm/lightdm.log
> [+0.00s] DEBUG: Starting Light Display Manager 1.30.0, UID=0 PID=33005
> [+0.00s] DEBUG: Loading configuration dirs from /usr/share/lightdm/lightdm.conf.d
> [+0.00s] DEBUG: Loading configuration dirs from /usr/local/share/lightdm/lightdm.conf.d
> [+0.00s] DEBUG: Loading configuration dirs from /etc/xdg/lightdm/lightdm.conf.d
> [+0.00s] DEBUG: Loading configuration from /etc/lightdm/lightdm.conf.d/20-optimus-manager.conf
> [+0.00s] DEBUG:   [SeatDefaults] is now called [Seat:*], please update this configuration
> [+0.00s] DEBUG: Loading configuration from /etc/lightdm/lightdm.conf
> [+0.00s] DEBUG: Registered seat module local
> [+0.00s] DEBUG: Registered seat module xremote
> [+0.00s] DEBUG: Using D-Bus name org.freedesktop.DisplayManager
> [+0.00s] DEBUG: _g_io_module_get_default: Found default implementation local (GLocalVfs) for ‘gio-vfs’
> [+0.00s] DEBUG: Monitoring logind for seats
> [+0.00s] DEBUG: New seat added from logind: seat0
> [+0.00s] WARNING: Seat type 'xlocal' is deprecated, use 'type=local' instead
> [+0.00s] DEBUG: Seat seat0: Loading properties from config section Seat:*
> [+0.00s] DEBUG: Seat seat0: Starting
> [+0.00s] DEBUG: Seat seat0: Creating greeter session
> [+0.00s] DEBUG: Seat seat0: Creating display server of type x
> [+0.00s] DEBUG: posix_spawn avoided (fd close requested) 
> [+0.00s] DEBUG: Could not run plymouth --ping: Failed to execute child process “plymouth” (No such file or directory)
> [+0.00s] DEBUG: Using VT 7
> [+0.00s] DEBUG: Seat seat0: Starting local X display on VT 7
> [+0.00s] DEBUG: XServer 0: Logging to /var/log/lightdm/x-0.log
> [+0.00s] DEBUG: XServer 0: Writing X server authority to /run/lightdm/root/:0
> [+0.00s] DEBUG: XServer 0: Launching X Server
> [+0.00s] DEBUG: Launching process 33011: /usr/bin/X :0 -seat seat0 -auth /run/lightdm/root/:0 -nolisten tcp vt7 -novtswitch
> [+0.00s] DEBUG: XServer 0: Waiting for ready signal from X server :0
> [+0.00s] DEBUG: Acquired bus name org.freedesktop.DisplayManager
> [+0.00s] DEBUG: Registering seat with bus path /org/freedesktop/DisplayManager/Seat0
> [+0.00s] DEBUG: Loading users from org.freedesktop.Accounts
> [+0.00s] DEBUG: User /org/freedesktop/Accounts/User1000 added
> [+0.01s] DEBUG: posix_spawn avoided (automatic reaping requested) (fd close requested) 
> [+1.06s] DEBUG: Got signal 10 from process 33011
> [+1.06s] DEBUG: XServer 0: Got signal from X server :0
> [+1.06s] DEBUG: XServer 0: Connecting to XServer :0
> [+1.11s] DEBUG: Launching process 33026: /sbin/prime-offload
> [+1.22s] DEBUG: Process 33026 exited with return value 0
> [+1.22s] DEBUG: Seat seat0: Exit status of /sbin/prime-offload: 0
> [+1.22s] DEBUG: posix_spawn avoided (fd close requested) (child_setup specified) 
> [+1.22s] DEBUG: Seat seat0: Display server ready, starting session authentication
> [+1.22s] DEBUG: Session pid=33033: Started with service 'lightdm-greeter', username 'lightdm'
> [+1.23s] DEBUG: Session pid=33033: Authentication complete with return value 0: Success
> [+1.23s] DEBUG: Seat seat0: Session authenticated, running command
> [+1.23s] DEBUG: Session pid=33033: Running command /usr/bin/lightdm-webkit2-greeter
> [+1.23s] DEBUG: Creating shared data directory /var/lib/lightdm-data/lightdm
> [+1.23s] DEBUG: Session pid=33033: Logging to /var/log/lightdm/seat0-greeter.log
> [+1.23s] DEBUG: Activating VT 7
> [+1.23s] DEBUG: Activating login1 session c6
> [+1.23s] DEBUG: Seat seat0 changes active session to c6
> [+1.23s] DEBUG: Session c6 is already active
> [+1.54s] DEBUG: Greeter connected version=1.30.0 api=1 resettable=false
> [+1.65s] DEBUG: Greeter requests data directory for user andre
> [+1.65s] DEBUG: Creating shared data directory /var/lib/lightdm-data/andre
> [+3.48s] DEBUG: Greeter start authentication for andre
> [+3.48s] DEBUG: Session pid=33108: Started with service 'lightdm', username 'andre'
> [+3.50s] DEBUG: Session pid=33108: Got 1 message(s) from PAM
> [+3.50s] DEBUG: Prompt greeter with 1 message(s)
> [+6.91s] DEBUG: Continue authentication
> [+6.93s] DEBUG: Session pid=33108: Authentication complete with return value 0: Success
> [+6.93s] DEBUG: Authenticate result for user andre: Success
> [+6.93s] DEBUG: User andre authorized
> [+7.93s] DEBUG: Greeter requests session gnome-xorg
> [+7.96s] DEBUG: Writing /home/andre/.dmrc
> [+7.98s] DEBUG: Seat seat0: Stopping greeter; display server will be re-used for user session
> [+7.98s] DEBUG: Terminating login1 session c6
> [+7.99s] DEBUG: Session pid=33033: Sending SIGTERM
> [+8.00s] DEBUG: Session pid=33033: Exited with return value 1
> [+8.00s] DEBUG: Seat seat0: Session stopped
> [+8.00s] DEBUG: Seat seat0: Greeter stopped, running session
> [+8.00s] DEBUG: Registering session with bus path /org/freedesktop/DisplayManager/Session0
> [+8.00s] DEBUG: posix_spawn avoided (fd close requested) (child_setup specified) 
> [+8.00s] DEBUG: Session pid=33108: Running command /etc/lightdm/Xsession /usr/bin/gnome-session
> [+8.00s] DEBUG: Creating shared data directory /var/lib/lightdm-data/andre
> [+8.01s] DEBUG: Session pid=33108: Logging to .xsession-errors
> [+8.03s] DEBUG: Activating VT 7
> [+8.03s] DEBUG: Activating login1 session 15
> [+8.03s] DEBUG: Seat seat0 changes active session to 15
> [+8.03s] DEBUG: Session 15 is already active
> [+3257.06s] DEBUG: Session pid=33108: Exited with return value 0
> [+3257.06s] DEBUG: Seat seat0: Session stopped
> [+3257.06s] DEBUG: Seat seat0: Stopping display server, no sessions require it
> [+3257.06s] DEBUG: Sending signal 15 to process 33011
> [+3257.65s] DEBUG: Process 33011 exited with return value 0
> [+3257.65s] DEBUG: XServer 0: X server stopped
> [+3257.65s] DEBUG: Releasing VT 7
> [+3257.65s] DEBUG: XServer 0: Removing X server authority /run/lightdm/root/:0
> [+3257.65s] DEBUG: Seat seat0: Display server stopped
> [+3257.65s] DEBUG: Launching process 71484: /sbin/prime-switch
> [+3257.97s] DEBUG: Process 71484 exited with return value 0
> [+3257.97s] DEBUG: Seat seat0: Exit status of /sbin/prime-switch: 0
> [+3257.97s] DEBUG: Seat seat0: Active display server stopped, starting greeter
> [+3257.97s] DEBUG: Seat seat0: Creating greeter session
> [+3257.97s] DEBUG: Seat seat0: Creating display server of type x
> [+3257.97s] DEBUG: Using VT 7
> [+3257.97s] DEBUG: Seat seat0: Starting local X display on VT 7
> [+3257.97s] DEBUG: XServer 0: Logging to /var/log/lightdm/x-0.log
> [+3257.97s] DEBUG: XServer 0: Writing X server authority to /run/lightdm/root/:0
> [+3257.97s] DEBUG: XServer 0: Launching X Server
> [+3257.97s] DEBUG: Launching process 71514: /usr/bin/X :0 -seat seat0 -auth /run/lightdm/root/:0 -nolisten tcp vt7 -novtswitch
> [+3257.97s] DEBUG: XServer 0: Waiting for ready signal from X server :0
> [+3258.98s] DEBUG: Got signal 10 from process 71514
> [+3258.98s] DEBUG: XServer 0: Got signal from X server :0
> [+3258.98s] DEBUG: XServer 0: Connecting to XServer :0
> [+3259.03s] DEBUG: Launching process 71527: /sbin/prime-offload
> [+3259.15s] DEBUG: Process 71527 exited with return value 0
> [+3259.15s] DEBUG: Seat seat0: Exit status of /sbin/prime-offload: 0
> [+3259.15s] DEBUG: posix_spawn avoided (fd close requested) (child_setup specified) 
> [+3259.15s] DEBUG: Seat seat0: Display server ready, starting session authentication
> [+3259.15s] DEBUG: Session pid=71534: Started with service 'lightdm-greeter', username 'lightdm'
> [+3259.16s] DEBUG: Session pid=71534: Authentication complete with return value 0: Success
> [+3259.16s] DEBUG: Seat seat0: Session authenticated, running command
> [+3259.16s] DEBUG: Session pid=71534: Running command /usr/bin/lightdm-webkit2-greeter
> [+3259.16s] DEBUG: Creating shared data directory /var/lib/lightdm-data/lightdm
> [+3259.16s] DEBUG: Session pid=71534: Logging to /var/log/lightdm/seat0-greeter.log
> [+3259.21s] DEBUG: Activating VT 7
> [+3259.21s] DEBUG: Activating login1 session c7
> [+3259.21s] DEBUG: Seat seat0 changes active session to c7
> [+3259.21s] DEBUG: Session c7 is already active
> [+3259.54s] DEBUG: Greeter connected version=1.30.0 api=1 resettable=false
> [+3261.38s] DEBUG: Greeter start authentication for andre
> [+3261.39s] DEBUG: Session pid=71627: Started with service 'lightdm', username 'andre'
> [+3261.40s] DEBUG: Session pid=71627: Got 1 message(s) from PAM
> [+3261.40s] DEBUG: Prompt greeter with 1 message(s)
> [+3265.90s] DEBUG: Continue authentication
> [+3265.92s] DEBUG: Session pid=71627: Authentication complete with return value 0: Success
> [+3265.92s] DEBUG: Authenticate result for user andre: Success
> [+3265.92s] DEBUG: User andre authorized
> [+3265.92s] DEBUG: Greeter requests session default
> [+3265.95s] DEBUG: Writing /home/andre/.dmrc
> [+3265.96s] DEBUG: Seat seat0: Failed to find session configuration default
> [+3265.96s] DEBUG: Seat seat0: Can't find session 'default'

</details>

Seems the problem is in:

> [+3265.96s] DEBUG: Seat seat0: Failed to find session configuration default
> [+3265.96s] DEBUG: Seat seat0: Can't find session 'default'

I am realatively new to arch so maybe I did configure something wrong? I was previously using antergos theme using the exact same greeter and everything works correctly.

**Comment by paysonwallach** [comment]
Oh, no worries! In `/etc/lightdm/lightdm.conf`, verify that `user-session` is set to your desktop session, e.g. `gnome` (You can find a list of installed sessions in `/usr/share/xsessions`).

**Comment by andrfgs** [comment]
Thank you so much. I was indeed using gnome and that solved the problem. I wonder why the default theme worked anyway.

Anyways, the problem is solved. Thank you very much!

**Comment by paysonwallach** [comment]
I'm glad that worked! The default theme does have a feature I've been meaning to implement for a while that is letting the user select a session to log into. I guess this could be another benefit of that feature.
