### ISSUE TITLE
The password box doesn't work

### ISSUE THREAD

**Issue by ghost** [paysonwallach/aqua-lightdm-webkit-theme#11]
I installed this theme on webkit2 greeter and it looks very good. But when I enter my password, it does'nt do nothing. 

I tried to use the lightdm test mode, but mouse and keyboard doesn't work. And in `lightdm-webkit2-greeter ` doesn't work any button

**Comment by robbins** [comment]
Same for me, did you ever find a fix?

**Comment by paysonwallach** [comment]
Are there any errors in `lightdm.log` or `seat0-greeter.log`? (You may need to drop down to `root` to access them, as they're located in `/var/log/lightdm/`.)

**Comment by robbins** [comment]
> Are there any errors in `lightdm.log` or `seat0-greeter.log`? (You may need to drop down to `root` to access them, as they're located in `var/log/lightdm/`.)

Thanks so much, it told me session-default not found and then I realized I didn't have user-session set in Seat:*, I had it in another section.

Thanks for the help :) great theme btw

**Comment by paysonwallach** [comment]
Glad you were able to find the solution and I'm glad you like the theme!

**Comment by paysonwallach** [comment]
Closing this issue until @algunacosa has any further comments.
