### ISSUE TITLE
lightdm.default_session returned error code 1

### ISSUE THREAD

**Issue by ray1422** [paysonwallach/aqua-lightdm-webkit-theme#13]
This theme works on my laptop with Mint, but when I try to install this theme on Lubuntu and Arch Linux, I can't login.
I've tried to figure out what's went wrong and found the cause of the error is located at greeters.js line 110 `lightdm.default_session`
I simply wrap this line with try-catch and it shows error message "lightdm.default_session returned error code 1".
I'll try to fix it and make a pull request.
https://github.com/paysonwallach/aqua-lightdm-webkit-theme/blob/e8dcfdf2db27dac5e4ace22ad3a9e55d4122e240/resources/js/greeter.js#L110

**Comment by ray1422** [comment]
I just replace `lightdm.default_session` with `lightdm.sessions[0].key` and it works correctly.
but I will make a selector for selecting sessions.

**Comment by paysonwallach** [comment]
I believe `user-session` needs to be set in `/etc/lightdm/lightdm.conf`. I'm glad you were able to figure a solution. A session selector has definitely been on the to-do list for some time now.
