### ISSUE TITLE
Can't change background image

### ISSUE THREAD

**Issue by jpmvferreira** [paysonwallach/aqua-lightdm-webkit-theme#3]
After trying to copy my image to `usr/share/background/current` as specified in `style.css`, i had an error and asked my if i wanted to use my default theme, the fallback theme or cancel.

When trying to change the default image to a path in my home directory (mounted on a separate partition but it's mounted before login) in `style.css` and removing the background-color variable even, the background image does not show up.

**Comment by paysonwallach** [comment]
Sounds like it could be a permissions issue. Is the image file readable by everyone?

**Comment by jpmvferreira** [comment]
After trying to change the directory of the file, which didn't work, i've used `chmod 777` and changed it owner to root, and it works as expected, however adding an extension to the file name, such as `.jpg`, made it not show up in the login scren, but i do confess, i've yet to understand permissions in linux, so it might have been something that i did wrong along the way.

Thanks!

**Comment by paysonwallach** [comment]
Glad to hear that you got it working! I would recommend against setting file permissions to `777`, as it's a security risk, and `644` is sufficient in this case. You're correct that the symlink must be owned by `root`, but I don't believe the source image needs to be, thus you can simply use the following command to set the background image:

```
[sudo] ln -sf /path/to/image /usr/share/backgrounds/current
```

With regard to file extensions, unix essentially treats the extension as part of the filename, and would consider `current` and `current.jpg` to be different files. The reason for using a symlink to the desired image is purely to make my life easier, as I don't have to mess with reading a config file for one option, however I may consider such an implementation if users find it more intuitive.
