### ISSUE TITLE
Add option to allow bitmap image formats

### ISSUE THREAD

**Issue by jpmvferreira** [paysonwallach/aqua-lightdm-webkit-theme#4]
Having a custom avatar is much easier using something like .png or .jpg rather than .svg

**Comment by paysonwallach** [comment]
LightDM sets avatar images via [accountsservice](https://gitlab.freedesktop.org/accountsservice/accountsservice). The ArchWiki [LightDM entry](https://wiki.archlinux.org/index.php/LightDM#Changing_your_avatar) has an excellent explanation of how to configure it.
