### ISSUE TITLE
Blur creates dark outline

### ISSUE THREAD

**Issue by ciriousjoker** [paysonwallach/aqua-lightdm-webkit-theme#5]
This wouldn't happen if you layer the blurred image on top of the image. Then there would be no black background shining through.

**Comment by paysonwallach** [comment]
Thank you for pointing this out! I've never noticed it prominently on my laptop's display so I always thought it was a bug in the development VM. Unfortunately the outline was still noticeable after trying the solution you suggested, however I believe I found a good compromise by scaling the background image by a small factor to hide the outline. This has been implemented in version 0.4.1.

**Comment by ciriousjoker** [comment]
@paysonwallach yeah that also works. Thanks for the quick fix!
