### ISSUE TITLE
Scrollbars since last commit

### ISSUE THREAD

**Issue by ciriousjoker** [paysonwallach/aqua-lightdm-webkit-theme#6]
Actually, upscaling the background image doesn't quite work (from #5)
You forgot to set
`overflow: hidden`
and now there are scrollbars where I can move the whole container including the login prompt and the time in the upper right corner.

**Comment by paysonwallach** [comment]
Thanks! Added to 0.4.2. Can you confirm that this resolves the issue? (I didn't experience this in my tests.)

**Comment by ciriousjoker** [comment]
Issue still persists.. What's even weirder though, is that the wallpaper isn't found (black screen) and that I can't login. A wrong password shakes the box, but a correct one doesn't log me in. I'm using KDE. I'll create separate issues for that though..

EDIT: Was wrong about the shaking, that doesnt happen

**Comment by ciriousjoker** [comment]
Btw., the overflow hidden has to be on the body i think

**Comment by ciriousjoker** [comment]
Here's the change:
#9

**Comment by paysonwallach** [comment]
#9 merged, closing.
