### ISSUE TITLE
Black screen / No wallpaper

### ISSUE THREAD

**Issue by ciriousjoker** [paysonwallach/aqua-lightdm-webkit-theme#8]
Title says it all, I linked /usr/share/backgrounds/current to a jpg file, but it doesn't show up.

**Comment by ciriousjoker** [comment]
Issue was fixed by not symlinking to the wallpaper and instead copying it. Not optimal but whatever, for my case it works.

**Comment by paysonwallach** [comment]
The wallpaper image needs to be readable by the LightDM user. Until I can devise a better solution, I'll update the documentation to make a note of this (The reason behind the idea of using a symlink was to eliminate the need to worry about file extensions).

**Comment by ciriousjoker** [comment]
oh, then i think I chmodded the symlink.. my bad
